#!/usr/bin/env python

import sys
from daemon import Daemon
from sensor import GDIAlarmSensor

class SensorDaemon(Daemon):
  def run(self):
    sensor = GDIAlarmSensor(5000, 10000)
    sensor.run()

if __name__ == "__main__":
  daemon = SensorDaemon('/tmp/alarm-sensor.pid')
  if len(sys.argv) == 2:
    if 'start' == sys.argv[1]:
#      daemon.start()
      daemon.run()
    elif 'stop' == sys.argv[1]:
      daemon.stop()
    elif 'restart' == sys.argv[1]:
      daemon.restart()
    else:
      print "Unknown command"
      sys.exit(2)
    sys.exit(0)
  else:
    print "usage: %s start|stop|restart" % sys.argv[0]
    sys.exit(2)
